// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACq5kAQxjb4uy_Upg_RZ2_w4-4Anr2wCE',
    appId: '1:2207465858:web:ebf5a17cabce63ec1f0f9b',
    messagingSenderId: '2207465858',
    projectId: 'quize-fc8b9',
    authDomain: 'quize-fc8b9.firebaseapp.com',
    storageBucket: 'quize-fc8b9.appspot.com',
    measurementId: 'G-P16CSH12FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrlxw0dqzZhx7PPHVXYG5_rMVab1Ihie0',
    appId: '1:2207465858:android:627f43952be241691f0f9b',
    messagingSenderId: '2207465858',
    projectId: 'quize-fc8b9',
    storageBucket: 'quize-fc8b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9lWDGf98HSlK1Now2xQTzcrUpErUwzBg',
    appId: '1:2207465858:ios:268ea4102d58f1da1f0f9b',
    messagingSenderId: '2207465858',
    projectId: 'quize-fc8b9',
    storageBucket: 'quize-fc8b9.appspot.com',
    iosClientId: '2207465858-3tsdus9sp8ab7bseeghh2t3nj5p5e6me.apps.googleusercontent.com',
    iosBundleId: 'com.example.quize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9lWDGf98HSlK1Now2xQTzcrUpErUwzBg',
    appId: '1:2207465858:ios:268ea4102d58f1da1f0f9b',
    messagingSenderId: '2207465858',
    projectId: 'quize-fc8b9',
    storageBucket: 'quize-fc8b9.appspot.com',
    iosClientId: '2207465858-3tsdus9sp8ab7bseeghh2t3nj5p5e6me.apps.googleusercontent.com',
    iosBundleId: 'com.example.quize',
  );
}
